### ISSUE TITLE
width/height are switched

### ISSUE THREAD

**Issue by Prinzhorn** [rfrench/gify#2]
I guess this repo is inactive but for everyone forking it / building upon it: width and height are switched.

Those two lines https://github.com/rfrench/gify/blob/5ed5d01f2d70c8ac589fa5c5c513183bf38d563b/gify.js#L101 should read

``` js
info.width = view.getUint16(6, true);
info.height = view.getUint16(8, true);
```

**Comment by rfrench** [comment]
I wouldn't say it's inactive, I just haven't seen the need to add anything else to it. Once I verify the bug you reported, I'll update the repo.

Thanks

**Comment by Prinzhorn** [comment]
Great thanks. I forked it for my needs (dropped jDataView, added tests, pushed to npm). https://github.com/Prinzhorn/gif-info

**Comment by rfrench** [comment]
Looks great!

I pushed the fix as well as the changes that Beppe requested last year. Let me know if you want to see any other changes. Thanks again!
