### ISSUE TITLE
issue on loopCount

### ISSUE THREAD

**Issue by tutunci** [rfrench/gify#3]
Hi,
I'm using this library, I've an issue about loopCount, seems that even if is set a value of loops inside the gif I've always back loopCount=0.
Attached example is an animated gif with two frames (one sec each) and 15 loops.

![astrifox_160x600-30](https://cloud.githubusercontent.com/assets/400177/15044656/61bbf6de-12d6-11e6-876a-f64cd08d7b11.gif)

Thanks
Maurizio

**Comment by rfrench** [comment]
I just pushed a fix. Please re-open if this doesn't resolve the issue. Thanks for reporting it!
