### ISSUE TITLE
How to distinguish between loop once and loop forever?

### ISSUE THREAD

**Issue by tofrankie** [rfrench/gify#7]
I have three GIF images:
* `no-loopcount.gif`
* `loopcount-forever.gif`
* `loopcount-2.gif`

Their actual LoopCount is as follows (use [Gifsicle](https://www.lcdf.org/gifsicle/man.html)):

* `no-loopcount.gif` showing every frame **once**.
* `loopcount-forever.gif` showing **foreve**r (infitine).
* `loopcount-2.gif` showing every frame **thrice**.

![image](https://user-images.githubusercontent.com/26947203/209932957-b51a6a86-4878-44cd-aee4-9d768a2ae503.png)

But when I use `gify`, the result is:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/26947203/209934338-58eb7ecd-97e4-4229-8b28-ffb97f09b6f1.png">

The LoopCount parsed by `no-loopcount.gif` and `loopcount-forever.gif` are both `0`. 

**Is this a bug, or can't tell the difference?**

Here's how I do it:

```js
const getGifInfo = async file => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = event => {
      const URL = window.URL || window.webkitURL
      const blob = new Blob([event.target.result])
      const blobURL = URL.createObjectURL(blob)

      const img = new Image()
      img.src = blobURL
      img.onload = () => {
        const gifInfo = window.gify.getInfo(reader.result)
        resolve(gifInfo)
      }
      img.onerror = event => {
        reject(event)
      }
    }
    reader.readAsArrayBuffer(file)
  })
}
```

Thanks.

**Comment by rfrench** [comment]
Quickly looking at the code, I think the issue is because the loopCount defaults to 0 and if the loop count does not exist, it uses the default. Maybe the better option would be to default to 1 although you'd need to leverage both the isAnimated and loopCount to know it's an animated gif

**Comment by tofrankie** [comment]
Related Link: [Netscape Looping Application Extension](http://www.vurdalakov.net/misc/gif/netscape-looping-application-extension)

First, Loop Count flag is stored in the Application Extension, which is standardized by Netscape, not the official GIF standard. But due to its ubiquity, almost all software follows this standard.

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/26947203/220056258-0f0bb953-bf4e-4a30-bbf7-3b5f11389e17.png">

After testing, the following conclusions were drawn:

* If GIF exported by Photoshop without loop, the Application Extension does not contain the `NETSCAPE` identifier, only the `XMP Data` identifier.
* If GIF loops forever or loops n times (n > 0), the `NETSCAPE` identifier must be present in the Application Extension.

Therefore, we can read Loop Countdown correctly by modifying `gify.js`:

```js
  // ...
+ var hasNetscapeIdentifier = false

  // ...

  pos += 2
  var subBlock = readSubBlock(view, pos, true)
  switch (type) {
    case 0xff: //APPLICATION EXTENSION
      /* since multiple application extension blocks can
          occur, we need to make sure we're only setting
          the loop count when the identifer is NETSCAPE */
      var identifier = view.getString(8, pos + 1)
      if (identifier === 'NETSCAPE') {
+       hasNetscapeIdentifier = true
        info.loopCount = view.getUint8(pos + 14, true)
      } else if (identifier === 'XMP Data') {
+       if (!hasNetscapeIdentifier) info.loopCount = -1
      }
      break
    case 0xce: //NAME
      /* the only reference to this extension I could find was in
          gifsicle. I'm not sure if this is something gifsicle just
          made up or if this actually exists outside of this app */
      image.identifier = subBlock.data
      break
    case 0xfe: //COMMENT EXTENSION
      image.comments.push(subBlock.data)
      break
    case 0x01: //PLAIN TEXT EXTENSION
      image.text = subBlock.data
      break
  }
```

Irrelevant code omitted above. 
The modified Loop Count is represented as follows:

* `-1`: means no loop.
* `0`: means loop forever.
* `n`: means looping `n` times (`n + 1` impressions per frame).

**Comment by rfrench** [comment]
Could the same effect be achieved by doing something like this?

```
var info = {
   ...
   loopCount: -1,
   ...
}
```

It's been a really long time since I've looked at the GIF spec, but I could of sworn that XMP data was also optional, so I'm not sure that will always work when loop count isn't set.

**Comment by tofrankie** [comment]
> Could the same effect be achieved by doing something like this?
> 
> ```
> var info = {
>    ...
>    loopCount: -1,
>    ...
> }
> ```
> 
> It's been a really long time since I've looked at the GIF spec, but I could of sworn that XMP data was also optional, so I'm not sure that will always work when loop count isn't set.

they are the same.

**Comment by rfrench** [comment]
If you want to send a PR, I'll merge it.
